### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by yangyang-pro** [AbductiveLearning/ABL-KG#1]
Hi @Tony-HYX @AbductiveLearning 

Thanks for the nice work! When the code can be released?

**Comment by Tony-HYX** [comment]
Hi yangyang,

Firstly, my apologies for the late response. Thank you so much for your kind words and interest in the work!

I'm pleased to inform you that the initial version of the code has now been uploaded to the repository. Please feel free to check it out. Do note that there might be further updates in the future to improve functionality or address any issues.

Thanks again for your support!

Best regards.

**Comment by yangyang-pro** [comment]
Thank you very much!
